server:
  port: 8334
  servlet:
    context-path: /api/linda
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 数据库字段映射Java驼峰属性名
    # 仅在开发环境开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  application:
    name: linda-brain
  # 数据库配置
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/linda
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
    slave1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/linda
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
    slave2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/linda
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    timeout: 3000
    lettuce:
      pool:
        max-active: 20   # 最大活跃连接数（默认8）
        max-idle: 10     # 最大空闲连接数（默认8）
        min-idle: 3      # 最小空闲连接数（默认0）
        max-wait: 5000   # 获取连接最大等待时间（毫秒，默认-1无限等待）
    ssl: false
  # Kafka配置
  kafka:
    bootstrap-servers: 192.168.1.22:9094
    producer:
      # 生产者重试次数
      retries: 3
      # 批量发送的记录数量
      batch-size: 16384
      # 缓冲区大小
      buffer-memory: 33554432
      # 键和值的序列化器
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      # 消费者组ID
      group-id: linda-websocket-group
      # 自动提交偏移量
      enable-auto-commit: true
      # 自动提交偏移量的间隔时间
      auto-commit-interval: 1000
      # 键和值的反序列化器
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 当没有初始偏移量或服务器上不再存在当前偏移量时的策略
      auto-offset-reset: latest

# 日志配置
logging:
  config: file:./logback.xml  # 指定外部logback配置文件路径
  file:
    path: ./logs  # 日志文件路径，相对于jar包所在目录

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name} # 暴露的数据中添加application label
